### PR TITLE
Iron 0.4.0 upgrade

### LINKED ISSUE #17: Build failed on nightly rust
``` bash
😍  rust_lang_cn git:(master) ✗ cargo build --verbose
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/messense/.cargo/registry/src/github.com-1ecc6299db9ec823/iron-0.3.0/Cargo.toml`

Caused by:
  you have already provided an operation, such as =, ~, or ^; only use one
😍  rust_lang_cn git:(master) ✗ rustc --version
rustc 1.12.0-nightly (576f76659 2016-08-09)
😍  rust_lang_cn git:(master) ✗ cargo --version
cargo 0.13.0-nightly (c205132 2016-08-09)
```

看起来是 iron 0.3.0 的锅

### PR DESCRIPTION
**Pull request by messense**
1. Upgraded Iron to 0.4.0
2. Pined dependencies version in `Cargo.toml`
3. Add [Travis CI](https://travis-ci.org) configuration. (You have to enable it in Travis CI website.)

Fixes #17

### CODE REVIEW

**Comment by liyuan462** [comment]
你是用nightly编译的吧？我没编译过你的分支：
rustc -V
rustc 1.9.0 (e4e8b6668 2016-05-18)

`Running `rustc /root/.cargo/registry/src/github.com-88ac128001ac3a9a/html5ever-0.5.4/src/lib.rs --crate-name html5ever --crate-type lib -g -C metadata=1fcd3e24445d1337 -C extra-filename=-1fcd3e24445d1337 --out-dir /root/project/target/debug/deps --emit=dep-info,link -L dependency=/root/project/target/debug/deps -L dependency=/root/project/target/debug/deps --extern mac=/root/project/target/debug/deps/libmac-97fdf4d4ada74749.rlib --extern string_cache=/root/project/target/debug/deps/libstring_cache-467676219837e587.rlib --extern phf=/root/project/target/debug/deps/libphf-2ee21be9d70ecba9.rlib --extern time=/root/project/target/debug/deps/libtime-71756e48b8b5b73b.rlib --extern log=/root/project/target/debug/deps/liblog-342ffb7444a9471d.rlib --extern tendril=/root/project/target/debug/deps/libtendril-8ef247e66905753c.rlib --cap-lints allow`
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/io.rs:293:26: 293:47 error: use of unstable library feature 'unix_socket': newly added (see issue #32312)
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/io.rs:293     UnixStream(BufStream<unix::net::UnixStream>),
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:969:19: 969:49 error: use of unstable library feature 'unix_socket': newly added (see issue #32312)
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:969             match unix::net::UnixStream::connect(unix_addr) {
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:971:33: 971:49 error: use of unstable library feature 'unix_socket': newly added (see issue #32312)
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:971                     try!(stream.set_read_timeout(self.opts.get_read_timeout().clone()));
                                                                                                                      ^~~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:971:21: 971:89 note: in this expansion of try! (defined in <std macros>)
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:972:33: 972:50 error: use of unstable library feature 'unix_socket': newly added (see issue #32312)
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mysql-7.0.0/src/conn/mod.rs:972                     try!(stream.set_write_timeout(self.opts.get_write_timeout().clone()));
                                                                                                                      ^~~~~~~~~~~~~~~~~`

**Comment by messense** [comment]
用的 stable 版本，stable 已经是 1.10 了，为什么还在用 1.9.0

**Comment by messense** [comment]
``` bash
😍  rust_lang_cn git:(feature/iron-0-4-upgrade) rustc --version
rustc 1.10.0 (cfcb716cf 2016-07-03)
😍  rust_lang_cn git:(feature/iron-0-4-upgrade) cargo --version
cargo 0.11.0-nightly (259324c 2016-05-20)
😍  rust_lang_cn git:(feature/iron-0-4-upgrade) cargo build
   Compiling winapi-build v0.1.1
   Compiling void v1.0.2
   Compiling semver v0.1.20
   Compiling lazy_static v0.2.1
   Compiling rustc-serialize v0.3.19
   Compiling traitobject v0.0.1
   Compiling fnv v1.0.3
   Compiling route-recognizer v0.1.11
   Compiling lazy_static v0.1.16
   Compiling regex-syntax v0.3.4
   Compiling byteorder v0.5.3
   Compiling mac v0.0.2
   Compiling serde v0.7.15
   Compiling crossbeam v0.2.10
   Compiling kernel32-sys v0.2.2
   Compiling pkg-config v0.3.8
   Compiling unreachable v0.1.1
   Compiling nom v1.2.4
   Compiling rustc_version v0.1.7
   Compiling httparse v1.1.2
   Compiling serde v0.8.1
   Compiling dtoa v0.2.2
   Compiling unicase v1.4.0
   Compiling maplit v0.1.3
   Compiling libc v0.2.15
   Compiling debug_unreachable v0.1.1
   Compiling futf v0.1.2
   Compiling traitobject v0.0.3
   Compiling pest v0.3.3
   Compiling quick-error v1.1.0
   Compiling antidote v1.0.0
   Compiling humantime v0.1.3
   Compiling bufstream v0.1.2
   Compiling language-tags v0.2.2
   Compiling utf8-ranges v0.1.3
   Compiling num-traits v0.1.34
   Compiling num_cpus v0.2.13
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.2
   Compiling log v0.3.6
   Compiling mime v0.2.2
   Compiling hpack v0.2.0
   Compiling phf_shared v0.7.16
   Compiling typeable v0.1.2
   Compiling error v0.1.9
   Compiling encoding_index_tests v0.1.4
   Compiling modifier v0.1.0
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling phf v0.7.16
   Compiling num-integer v0.1.32
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling solicit v0.4.4
   Compiling num-iter v0.1.32
   Compiling RustyXML v0.1.1
   Compiling unsafe-any v0.4.1
   Compiling itoa v0.1.1
   Compiling num v0.1.34
   Compiling bitflags v0.5.0
   Compiling ordered-float v0.1.0
   Compiling bitflags v0.7.0
   Compiling rand v0.3.14
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling typemap v0.3.3
   Compiling plugin v0.2.6
   Compiling winapi v0.2.8
   Compiling encoding v0.2.32
   Compiling rss v0.3.1
   Compiling walkdir v0.1.5
   Compiling time v0.1.35
   Compiling conduit-mime-types v0.7.3
   Compiling thread-id v2.0.0
   Compiling toml v0.2.0
   Compiling twox-hash v1.0.0
   Compiling thread_local v0.2.6
   Compiling uuid v0.1.18
   Compiling phf_generator v0.7.16
   Compiling chrono v0.2.25
   Compiling getopts v0.2.14
   Compiling phf_codegen v0.7.16
   Compiling gcc v0.3.32
   Compiling html5ever v0.5.4
   Compiling unicode-normalization v0.1.2
   Compiling pulldown-cmark v0.0.8
   Compiling serde-value v0.2.1
   Compiling rust-crypto v0.2.36
   Compiling openssl v0.7.14
   Compiling openssl-sys-extras v0.7.14
   Compiling yaml-rust v0.3.3
   Compiling sequence_trie v0.0.13
   Compiling matches v0.1.2
   Compiling url v0.2.38
   Compiling unicode-bidi v0.2.3
   Compiling utf-8 v0.6.0
   Compiling tendril v0.2.2
   Compiling string_cache v0.2.23
   Compiling idna v0.1.0
   Compiling openssl-sys v0.7.15
   Compiling regex v0.1.73
   Compiling serde_yaml v0.2.5
   Compiling serde_json v0.8.1
   Compiling log4rs v0.4.8
   Compiling url v1.2.0
   Compiling openssl-verify v0.1.0
   Compiling cookie v0.2.5
   Compiling hyper v0.9.10
   Compiling mysql v7.0.0
   Compiling handlebars v0.20.3
   Compiling ammonia v0.1.2
   Compiling iron v0.4.0
   Compiling mount v0.2.1
   Compiling persistent v0.2.0
   Compiling router v0.2.0
   Compiling handlebars-iron v0.18.0
   Compiling oven v0.4.0
   Compiling bodyparser v0.4.1
   Compiling staticfile v0.3.0
   Compiling iron-login v0.5.0
   Compiling urlencoded v0.4.0
   Compiling rust_lang_cn v1.0.1 (file:///Users/messense/Projects/rust_lang_cn)
```

**Comment by messense** [comment]
@liyuan462 把 `mysql` 7.0 的 unix socket feature 关了，现在 Rust 1.9.0 可以编译通过了。

**Comment by liyuan462** [comment]
倒也不用，我正在升级rust

**Comment by messense** [comment]
@liyuan462 似乎 MySQL 的 unix socket 这个 feature 大家都不去用的，去掉编译还快些。

**Comment by messense** [comment]
@liyuan462 去配置一下 Travis CI，让 CI 自动跑 build 吧

**Comment by liyuan462** [comment]
好，我有空弄一下

**Pull request merged**
